### ISSUE TITLE
Urmet Callme

### ISSUE THREAD

**Issue by Al70777** [denisgabriel5/homebridge-intercom#1]
**Is your feature request related to a problem? Please describe:**

Would it be possible to have support for the Urmet 2 voice video intercom using the Callme app which forward the call to the app. 

Thank you

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by denisgabriel5** [comment]
Apparently, this kind of intercom is a closed system:

https://community.home-assistant.io/t/urmet-callme-intercom-app/629025/2

This means that there's no way to connect to the intercom without some sort of intervention on the intercom's main board. 

If you want, you can try to do some reverse engineering on the intercom and add something like a Shelly Uni or Raspberry Pi. Only then I could add support for it.
