### ISSUE TITLE
Shelly Plus Uni

### ISSUE THREAD

**Issue by tomnorton81** [denisgabriel5/homebridge-intercom#2]
Do you support the ‘Shelly Plus Uni’ as well as the ‘Shelly Uni’? Was considering buying one in the UK to try with my Fermax Door Intercom, however I can only see the ‘Plus’ version in a UK store.

Do you have any wiring diagrams at all on how you set it up?

Thanks

**Comment by denisgabriel5** [comment]
Hi @tomnorton81,

From my understanding they are basically the same regarding what we need. A friend of mine actually uses one, while I use the non Plus one and we both use this plug-in.

Regarding the wiring diagram, that is specific to your intercom. Shelly Uni Plus provides some callbacks that the plug-in uses. So, you would need a way to connect the Shelly device to your intercom. Best I can do is to offer you some advice based on my experience, but you'll have to do the main research regarding where and what to connect.

**Comment by tomnorton81** [comment]
Hi @denisgabriel5 

Thank you for responding so quickly. I’ll order the Plus Uni and see what I can do with my intercom.

At the moment my intercom is wired back to a TEMA relay unit, which in turn plugs into my FRITZBox Internet router as a phone extension. When someone presses the doorbell it rings the DECT phones in the house.

I’m assuming, that I could replace the TEMA with the Shelly Plus Uni and link it into HomeKit.

Just got to figure out what wire goes where!
![IMG_1784](https://github.com/user-attachments/assets/71b8c07f-bcc2-44bc-acc7-4d14db0ae7ba)
